# Indicate the subfolder of the input folder that contains the input files
transport_modes: [roads, maritime, waterways, railways]
monetary_units_in_model: mUSD
monetary_units_inputed: USD
time_resolution: day
io_cutoff: 0.2
inventory_duration_targets:
  definition: per_input_type
  values:
    utility: 1
    agriculture: 15
    manufacturing: 30
    service: 90
    trade: 30
    construction: 30
    transport: 3
    default: 30
  unit: day
basic_cost_random: False  # deactivate all randomness
basic_cost_variability: # coefficient of variation
  roads: 0.1
  maritime: 0.05
  airways: 0.01
  railways: 0.2
  waterways: 0.2
  pipelines: 0.01
  multimodal: 0.01
countries_to_include: ['AFR', 'AME', 'ASI', 'EUR', 'OCE', 'THA', 'VNM']
simulation_type: disruption  # disruption
export_files: True
t_final: 5
disruptions:
  - type: transport_disruption
    description_type: edge_attributes
    attribute: class
    values: ["tertiary"]
    start_time: 1
    duration: 1
# Filter out sectors firms output is below that cutoff value
cutoff_firm_output:
  'type': 'absolute'
  'value': 100
  "unit": "kUSD"

# Filter out region_sector to households links if purchase is below that cutoff value
cutoff_household_demand:
  'type': 'absolute'  # only absolute works
  'value': 100
  "unit": "kUSD"