# Indicate the subfolder of the input folder that contains the input files
filepaths:
  "sector_table": "Economic/sector_table.csv"
#  "inventory_duration_targets": "Network/inventory_targets.csv"
  "mrio": "Economic/mrio_BS_MC.csv"
  "railways_edges": "Transport/railways_edges_2030.geojson"
transport_modes: ["roads", "maritime", "railways", "pipelines"] #, waterways, airways]
monetary_units_in_model: mUSD
monetary_units_in_data: mUSD
time_resolution: day
io_cutoff: 0.2
cutoff_sector_demand:
  'type': 'absolute'
  'value': 1000
  'unit': 'kUSD'
cutoff_firm_output:
  'type': 'absolute'
  'value': 1000
  "unit": "kUSD"
cutoff_household_demand:
  'type': 'absolute'
  'value': 1000
  "unit": "kUSD"
nb_suppliers_per_input: 1  # 5
export_files: True
firm_data_type: mrio
weight_localization_household: 10
capacity_constraint: "off"
#logistics:
#  speeds: #km/hour
#    roads:
#      paved: 50
#      unpaved: 15
#    maritime: 35
#    railways: 35
#    waterways: 15
#    pipelines: 20
#  basic_cost: # per ton*km
#    roads: 0.1
#    maritime: 0.005
#    airways: 1
#    railways: 0.05
#    waterways: 0.005
#    pipelines: 0.0005
#    multimodal: 0.01
#  nb_cost_profiles: 1
#  basic_cost_random: True
#  name-specific:
#    turkmenbashi: 125.0
logistics:  # Sources: TRACECA Corridor Studies, ADB CAREC Logistics Costing, World Bank Central Asia Road Transport Surveys, OECD reports on Eurasian pipeline networks
  nb_cost_profiles: 1
  basic_cost_random: True

  speeds: # km/hour
    roads: 45                 # average for freight trucks across mountainous and steppe terrain
    maritime: 20              # Caspian Sea ferry/ro-ro avg speed
    railways: 35              # electrified main lines, non-high-speed (TRACECA average)
    pipelines: 10             # crude oil pipelines (transit rate)

  basic_cost: # USD per ton*km
    roads: 0.08               # relatively high due to long inland hauls and diesel costs
    maritime: 0.006           # ferry + port charges amortized over distance
    railways: 0.04            # lower cost on Kazakh and Azerbaijani mainlines
    pipelines: 0.0004         # very low, Kazakhstan CPC or KTO pipelines
    multimodal: 0.012         # rail-road, road-maritime blending costs

  dwell_times: # hours
    roads-maritime: 18        # Caspian Sea port handling can take 1–2 days
    roads-railways: 8         # intermodal terminals at Almaty, Baku, Tbilisi relatively efficient
    railways-maritime: 12     # direct ferry rail-car loading (e.g., Baku–Turkmenbashi)
    roads-pipelines: 4        # crude loading terminals (e.g., rail-to-pipe)
    railways-pipelines: 6     # fewer direct rail-pipe interfaces
    pipelines-maritime: 6     # port offloading terminal handling

  loading_fees: # USD/ton
    roads-maritime: 2.5       # Caspian ports slightly more expensive due to ferry prep
    roads-railways: 2.0
    railways-maritime: 2.5
    roads-pipelines: 1.2
    railways-pipelines: 1.0
    pipelines-maritime: 1.0

  border_crossing_fees: # USD/ton
    roads: 35                 # tariffs/permit fees common on road crossings
    maritime: 20              # typically lower at ferry ports
    railways: 25              # customs and wagon inspection fees
    pipelines: 3              # flat administrative throughput tariff

  border_crossing_times: # hours
    roads: 3                  # varies; can spike to 6+ on peak days
    maritime: 4               # ferry wait + clearance at Baku, Aktau, Turkmenbashi
    multimodal: 6             # road/rail to maritime adds coordination overhead
    railways: 2               # smoother border logistics due to intergovernmental rail treaties
    pipelines: 0              # no physical delay (continuous flow)

  cost_of_time: 0.45          # USD/hour per ton — approximated from regional time-value studies

  name-specific:
    turkmenbashi: 100.0

use_route_cache: True
simulation_type: disruption
mc_repetitions: 50
sensitivity:
  duration: [1,5,10,15,30,60,120,180,270,365]
  logistics.speeds.roads: [50,60]
mc_caching:
  transport_network: true  # Reuse transport network
  agents: true             # Reuse agents 
  sc_network: true        # Regenerate for stochastic variation
  logistic_routes: true   # Regenerate for stochastic variation
t_final: 365
epsilon_stop_condition: 1e-3
#criticality:
#  attribute: top_flow
#  edges: [aktau, baku, turkmenbashi, railways-GEO, railways-AZE, railways-KAZ]
#  duration: 1
disruptions:
#  - type: transport_disruption
#    description_type: edge_attributes
#    attribute: name
#    values: [railways-GEO-intervention]
#    start_time: 1
#    duration: 5
  - type: transport_disruption_probability
    description_type: edge_attributes
    attribute: name
    values: [railways-KAZ-S1]
    start_time: 1
    probability_duration_pairs: [
      [0.1, 5],
    ]
    scenario_duration: 10
  - type: transport_disruption_probability
    description_type: edge_attributes
    attribute: name
    values: [railways-KAZ-N1]
    start_time: 1
    probability_duration_pairs: [
      [0.05, 5],
    ]
    scenario_duration: 10
#  - type: transport_disruption_probability
#    description_type: edge_attributes
#    attribute: name
#    values: [railways-GEO-intervention]
#    probability_duration_pairs: [
#      [0.000548, 1],
#      [0.000274, 1],
#      [0.000137, 2],
#      [0.000055, 4],
#      [0.000027, 7],
#      [0.000055, 13],
#      [0.000005, 30],
#      [0.000003, 60]
#    ]
#    scenario_duration: 365