# Indicate the subfolder of the input folder that contains the input files
logging_level: info
transport_modes: [roads, maritime, waterways, airways]
monetary_units_in_model: mUSD
monetary_units_in_data: kUSD
time_resolution: day
with_transport: False
inventory_duration_targets:
  definition: per_input_type
  values:
    utility: 3
    agriculture: 15
    manufacturing: 30
    service: 90
    trade: 30
    construction: 30
    transport: 5
    default: 30
  unit: day
io_cutoff: 0.01  # 0.01
cutoff_sector_output:
  'type': absolute
  'value': 1.0
  'unit': mUSD
cutoff_sector_demand:
  'type': absolute
  'value': 100
  'unit': kUSD
utilization_rate: 1
adaptive_inventories: True
inventory_restoration_time: 90
nb_suppliers_per_input: 1
adaptive_supplier_weight: False
price_increase_threshold: 2
simulation_type: stationary_test  # initial_state, disruption
sensitivity:
  utilization_rate: [0.2, 1]
  adaptive_supplier_weight: [True, False]
  adaptive_inventories: [True, False]
  nb_suppliers_per_input: [1, 4]
  inventory_duration_targets.values.utility: [3, 15]
  inventory_duration_targets.values.transport: [3, 15]
t_final: 30
mc_repetitions: 0
export_files: True
capital_to_value_added_ratio: 3
capacity_constraint: False
disruptions:
  - type: capital_destruction
    start_time: 1
#    description_type: region_sector_file
    description_type: filter  # sectors_homogeneous
    filter:
      #region_sector: ['ECU_TRA', 'ECU_INM']
      subregion_province: ['AZUAY']
    destroyed_capital: 2510.0
#    region_sector_filepath: "Disruption/earthquake_capital_destruction.csv"
    unit: mUSD
    reconstruction_market: False
