# Indicate the subfolder of the input folder that contains the input files
logging_level: info
#admin: [province]
transport_modes: [roads, maritime, waterways, airways]
#transport_cost_data:
#  roads: surface-specific  # edge_attr-specific for TR2 (Ximena's data), surface-specific for TR1 (OSM data)
monetary_units_in_model: mUSD
monetary_units_in_data: kUSD
time_resolution: day
#inventory_duration_target: 2  # inputed
with_transport: True
inventory_duration_targets:
  definition: per_input_type
  values:
    utility: 1
    agriculture: 15
    manufacturing: 30
    service: 90
    trade: 30
    construction: 30
    transport: 3
    default: 30
  unit: day
#sectors_no_transport_network: ['utility', 'transport', 'trade', 'service']  # remove trade for mrio
io_cutoff: 0.01  # 0.01
cutoff_sector_output:
  'type': absolute
  'value': 1.0
  'unit': mUSD
cutoff_sector_demand:
  'type': absolute
  'value': 100
  'unit': kUSD
utilization_rate: 1
adaptive_inventories: True
inventory_restoration_time: 90
nb_suppliers_per_input: 1
adaptive_supplier_weight: True
price_increase_threshold: 2
simulation_type: initial_state  # initial_state, disruption
mc_repetitions: 5
export_files: True
capital_to_value_added_ratio: 3
capacity_constraint: False
duration_dic:
  0: 10
  1: 4
  2: 8
  3: 11
  4: 14
events:
  - type: capital_destruction
    start_time: 1
#    description_type: region_sector_file
    description_type: filter  # sectors_homogeneous
    filter:
      region_sector: ['ECU_TRA', 'ECU_INM']
      province: ['Esmeraldas', 'SantoDomingodelosTsachilas', "Manabi"]
    destroyed_capital: 2510.0
#    region_sector_filepath: "Disruption/earthquake_capital_destruction.csv"
    unit: mUSD
    reconstruction_market: False
